## Libraries

In [2]:
import danflow.data as data
import danflow.training as training
import danflow.visualization as visualization

import pandas as pd

## Load dataset

In [3]:
data.extract_zip(
    zip_path="../data/shuttle.zip",
    output_path="../data"
)

In [4]:
data.delimited_to_csv(
    input_path="../data/shuttle.trn",
    output_path="../data/train.csv"
)

In [5]:
df = pd.read_csv("../data/train.csv", header=None)
df.head()

    0   1   2  3   4   5   6   7   8  9
0  50  21  77  0  28   0  27  48  22  2
1  55   0  92  0   0  26  36  92  56  4
2  53   0  82  0  52  -5  29  30   2  1
3  37   0  76  0  28  18  40  48   8  1
4  37   0  79  0  34 -26  43  46   2  1

<h2 align="center">1. Data Understanding</h2>

Initial exploration of the dataset structure, features, and basic statistics.

### 1. Dataset Structure

Display summary information about the dataset including column names, data types, and non-null counts.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43500 entries, 0 to 43499
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       43500 non-null  int64
 1   1       43500 non-null  int64
 2   2       43500 non-null  int64
 3   3       43500 non-null  int64
 4   4       43500 non-null  int64
 5   5       43500 non-null  int64
 6   6       43500 non-null  int64
 7   7       43500 non-null  int64
 8   8       43500 non-null  int64
 9   9       43500 non-null  int64
dtypes: int64(10)
memory usage: 3.3 MB

### 2. Initial Statistical Insights
Provide descriptive statistics of numerical features including mean, standard deviation, and value ranges.

In [ ]:
df.describe()

,0,1,2,3,4,5,6,7,8,9
count,43500.000000,43500.000000,43500.000000,43500.000000,43500.000000,43500.000000,43500.000000,43500.000000,43500.000000,43500.000000
mean,48.249747,-0.205126,85.341563,0.262736,34.528782,1.298276,37.074552,50.899862,13.964598,1.700529
std,12.252618,78.142770,8.908602,41.004131,21.703409,179.486760,13.135557,21.463250,25.648404,1.354648
min,27.000000,-4821.000000,21.000000,-3939.000000,-188.000000,-13839.000000,-48.000000,-353.000000,-356.000000,1.000000
25%,38.000000,0.000000,79.000000,0.000000,26.000000,-5.000000,31.000000,37.000000,0.000000,1.000000
50%,45.000000,0.000000,83.000000,0.000000,42.000000,0.000000,39.000000,44.000000,2.000000,1.000000
75%,55.000000,0.000000,89.000000,0.000000,46.000000,5.000000,42.000000,60.000000,14.000000,1.000000
max,126.000000,5075.000000,149.000000,3830.000000,436.000000,13148.000000,105.000000,270.000000,266.000000,7.000000

### 3. Data Quality Assessment

Assess the dataset for potential data quality issues.

In [10]:
df.duplicated().sum()

np.int64(0)